from tkinter import*

window=Tk()
window.iconbitmap("C:\calculatortwo\icon\Calculatoricon.ico")
window.title("CALCULATOR")
window.geometry("335x387")
window.resizable(0,0)
window.configure(background="#5c6b69")
#label for output
result_label=Label(window,text="",fg="white",bg="#1d1f1e",width=50,height=3,font=("arial",10))
result_label.pack()
#buttons
btn1=Button(window,text="C",font=("arial",10,"bold"),width=8,height=3,bg="black",fg="white")
btn1.place(x=7,y=60)
btn2=Button(window,text="%",font=("arial",10,"bold"),width=8,height=3,bg="black",fg="white")
btn2.place(x=89,y=60)
btn3=Button(window,text="/",font=("arial",10,"bold"),width=8,height=3,bg="black",fg="white")
btn3.place(x=171,y=60)
btn4=Button(window,text="x",font=("arial",10,"bold"),width=8,height=3,bg="black",fg="white")
btn4.place(x=253,y=60)
##
btn1=Button(window,text="7",font=("arial",10,"bold"),width=8,height=3,bg="black",fg="white")
btn1.place(x=7,y=125)
btn2=Button(window,text="8",font=("arial",10,"bold"),width=8,height=3,bg="black",fg="white")
btn2.place(x=89,y=125)
btn3=Button(window,text="9",font=("arial",10,"bold"),width=8,height=3,bg="black",fg="white")
btn3.place(x=171,y=125)
btn4=Button(window,text="-",font=("arial",10,"bold"),width=8,height=3,bg="black",fg="white")
btn4.place(x=253,y=125)
###
btn1=Button(window,text="4",font=("arial",10,"bold"),width=8,height=3,bg="black",fg="white")
btn1.place(x=7,y=190)
btn2=Button(window,text="5",font=("arial",10,"bold"),width=8,height=3,bg="black",fg="white")
btn2.place(x=89,y=190)
btn3=Button(window,text="6",font=("arial",10,"bold"),width=8,height=3,bg="black",fg="white")
btn3.place(x=171,y=190)
btn4=Button(window,text="+",font=("arial",10,"bold"),width=8,height=3,bg="black",fg="white")
btn4.place(x=253,y=190)
####
btn1=Button(window,text="1",font=("arial",10,"bold"),width=8,height=3,bg="black",fg="white")
btn1.place(x=7,y=255)
btn2=Button(window,text="2",font=("arial",10,"bold"),width=8,height=3,bg="black",fg="white")
btn2.place(x=89,y=255)
btn3=Button(window,text="3",font=("arial",10,"bold"),width=8,height=3,bg="black",fg="white")
btn3.place(x=171,y=255)
btn4=Button(window,text="=",font=("arial",10,"bold"),width=8,height=7,bg="black",fg="white")
btn4.place(x=253,y=255)
#####
btn1=Button(window,text="0",font=("arial",10,"bold"),width=19,height=3,bg="black",fg="white")
btn1.place(x=7,y=320)
btn2=Button(window,text=".",font=("arial",10,"bold"),width=8,height=3,bg="black",fg="white")
btn2.place(x=171,y=320)


window.mainloop()
